// <auto-generated/>
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly:
    System.Diagnostics.CodeAnalysis.SuppressMessage(
        "StyleCop.CSharp.OrderingRules",
        "SA1200:Using directives must be placed correctly",
        Justification = "<Pending>")]
[assembly:
    System.Diagnostics.CodeAnalysis.SuppressMessage(
        "StyleCop.CSharp.NamingRules",
        "SA1309:Field names must not begin with underscore",
        Justification = "<Pending>",
        Scope = "member",
        Target = "~F:EasyDb.App._mLanguages")]
[assembly:
    System.Diagnostics.CodeAnalysis.SuppressMessage(
        "StyleCop.CSharp.ReadabilityRules",
        "SA1121:Use built-in type alias",
        Justification = "<Pending>",
        Scope = "member",
        Target = "~M:EasyDb.App.App_LanguageChanged(System.Object,System.EventArgs)")]
[assembly:
    System.Diagnostics.CodeAnalysis.SuppressMessage(
        "StyleCop.CSharp.DocumentationRules",
        "SA1633:File must have header",
        Justification = "<Pending>",
        Scope = "namespace",
        Target = "~N:EasyDb.Converters")]
[assembly:
    System.Diagnostics.CodeAnalysis.SuppressMessage(
        "StyleCop.CSharp.ReadabilityRules",
        "SA1101:Prefix local calls with this",
        Justification = "<Pending>",
        Scope = "member",
        Target = "~M:EasyDb.CustomControls.GeneralSettringsPage.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1309:Field names must not begin with underscore", Justification = "<Pending>", Scope = "member", Target = "~F:EasyDb.CustomControls.UserDatasouceSettingsControl._sourceOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File must have header", Justification = "<Pending>", Scope = "namespace", Target = "~N:EasyDb.View")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~P:EasyDb.ViewModel.MainViewModel.ActivePane")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~P:CSGO.Trader.ViewModel.Panes.PaneViewModel.IsActive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<Pending>", Scope = "member", Target = "~P:EasyDb.SandboxEnvironment.EdbModuleProxy.SupportDbModuleInstance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<Pending>")]

